version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - /app
            - /app/node_modules
        stdin_open: true
        ports:
            - 8080:8080
